const current_user = {
  "DUA_TO_GAO_RATE": 100,
  "SVIP_chef": 1,
  "SVIP_expired_date_chef": "Tue, 08 Dec 2020 00:00:00 +07",
  "SVIP_expired_date_loc": null,
  "SVIP_expired_date_special": null,
  "SVIP_loc": 0,
  "SVIP_special": 0,
  "VIP": 0,
  "VIP_expired_date": null,
  "apn_options": {
    "apn_bbox_found": true,
    "apn_bbox_voted": true,
    "apn_comment_forum": true,
    "apn_comment_voted": true,
    "apn_img_location_voted": true,
    "apn_img_reply_location_voted": true,
    "apn_location_forum": true,
    "apn_location_voted": true,
    "apn_login": true,
    "apn_matched_by_choice": true,
    "apn_matched_by_choice_loc": true,
    "apn_ranked_UP": true,
    "apn_replied_to_comment": true,
    "apn_replied_to_location": true,
    "apn_replied_to_submit": true,
    "apn_reply_comment_voted": true,
    "apn_reply_location_voted": true,
    "apn_reply_submit_voted": true,
    "apn_rewarded": true,
    "apn_submit_forum": true,
    "apn_submit_voted": true,
    "received_gift": true,
    "received_qr_gao": true
  },
  "background_caps": {
    "1": "",
    "2": "",
    "3": "",
    "4": "",
    "5": "",
    "6": "",
    "7": "",
    "8": "",
    "9": "",
    "10": ""
  },
  "background_imgs": {
    "1": "https://hatto.net//background_images/0cea0110-b54d-4406-bc9f-b4ff826dd40c/7d5003c6-d094-487f-be07-948da535e269.jpg",
    "2": "https://hatto.net//background_images/0cea0110-b54d-4406-bc9f-b4ff826dd40c/c7d5e5b6-bd5d-482f-a68f-5a574b8a86a7.jpg",
    "3": "https://hatto.net//background_images/0cea0110-b54d-4406-bc9f-b4ff826dd40c/6c9154b0-be52-4d83-9bbe-01a7e465b4db.jpg"
  },
  "background_url": "https://hatto.net//background_images/0cea0110-b54d-4406-bc9f-b4ff826dd40c/7d5003c6-d094-487f-be07-948da535e269.jpg",
  "birthday": "21/3/1995",
  "combined_geo": "",
  "comment_count": 0,
  "email": "lekhactruongphat347@gmail.com",
  "favorite_count": 0,
  "firebase_uid": "0cea0110-b54d-4406-bc9f-b4ff826dd40c",
  "frontpage_options": {
    "default_forum_fp": 0,
    "frontpage_view_option": 0
  },
  "gender": "0",
  "geo_country": "",
  "geo_level_1": "",
  "geo_level_2": "",
  "gifts": [
    {
      "category_desc": "Món ăn ngon",
      "category_html": null,
      "category_id": "mon_an",
      "category_url": "https://hatto.net//gift/Category/Mon_an_ngon.png",
      "gifts": [
        {
          "category_desc": "Món ăn ngon",
          "category_html": null,
          "category_id": "mon_an",
          "category_url": "https://hatto.net//gift/Category/Mon_an_ngon.png",
          "discount_per": null,
          "dynamic": 0,
          "dynamic_codes": {},
          "expiry_date": null,
          "gift_count": 1,
          "gift_desc": "Đĩa nem rán",
          "gift_html": null,
          "gift_id": "dia_nem_ran",
          "gift_long_desc": null,
          "gift_url": "https://hatto.net//gift/Mon_an_ngon/dia_nem_ran.png",
          "trans_id": ""
        },
        {
          "category_desc": "Món ăn ngon",
          "category_html": null,
          "category_id": "mon_an",
          "category_url": "https://hatto.net//gift/Category/Mon_an_ngon.png",
          "discount_per": null,
          "dynamic": 0,
          "dynamic_codes": {},
          "expiry_date": null,
          "gift_count": 1,
          "gift_desc": "Đĩa bánh cuốn nhân thịt",
          "gift_html": null,
          "gift_id": "dia_banh_cuon",
          "gift_long_desc": null,
          "gift_url": "https://hatto.net//gift/Mon_an_ngon/dia_banh_cuon.png",
          "trans_id": ""
        },
        {
          "category_desc": "Món ăn ngon",
          "category_html": null,
          "category_id": "mon_an",
          "category_url": "https://hatto.net//gift/Category/Mon_an_ngon.png",
          "discount_per": null,
          "dynamic": 0,
          "dynamic_codes": {},
          "expiry_date": null,
          "gift_count": 2,
          "gift_desc": "Bát bún chả",
          "gift_html": null,
          "gift_id": "bat_bun_cha",
          "gift_long_desc": null,
          "gift_url": "https://hatto.net//gift/Mon_an_ngon/bat_bun_cha.png",
          "trans_id": ""
        },
        {
          "category_desc": "Món ăn ngon",
          "category_html": null,
          "category_id": "mon_an",
          "category_url": "https://hatto.net//gift/Category/Mon_an_ngon.png",
          "discount_per": null,
          "dynamic": 0,
          "dynamic_codes": {},
          "expiry_date": null,
          "gift_count": 1,
          "gift_desc": "Lẩu mắm",
          "gift_html": null,
          "gift_id": "lau_mam",
          "gift_long_desc": null,
          "gift_url": "https://hatto.net//gift/Mon_an_ngon/lau_mam.png",
          "trans_id": ""
        }
      ]
    },
    {
      "category_desc": "Phiếu giảm giá",
      "category_html": "Quà tặng giảm giá khi trải nghiệm tại các Nhà hàng Chính danh",
      "category_id": "national_coupons",
      "category_url": "https://hatto.net//gift/National_coupons/folder.jpg",
      "gifts": [
        {
          "category_desc": "Phiếu giảm giá",
          "category_html": "Quà tặng giảm giá khi trải nghiệm tại các Nhà hàng Chính danh",
          "category_id": "national_coupons",
          "category_url": "https://hatto.net//gift/National_coupons/folder.jpg",
          "discount_per": 10,
          "dynamic": 0,
          "dynamic_codes": {},
          "expiry_date": null,
          "gift_count": 1,
          "gift_desc": "Giảm 10%",
          "gift_html": "<b>Lưu ý:</b><p><ul><li> Vui lòng đưa mã giảm giá này dạng QR khi thanh toán tại quầy thu nhận của cửa hàng<br><li>Mã giảm này không có gía trị quy đổi thành tiền mặt</ul></p>",
          "gift_id": "coupons_chinh_danh_10_per",
          "gift_long_desc": "Giảm giá <b>toàn bữa ăn 10%</b> khi trải nghiệm ẩm thực tại các Chính danh của Hatto chấp nhận Phiếu giảm giá này.",
          "gift_url": "https://hatto.net//gift/Coupon/giam_gia_10.png",
          "trans_id": ""
        }
      ]
    },
    {
      "category_desc": "Điện thoại di động",
      "category_html": null,
      "category_id": "dien_thoai",
      "category_url": "https://hatto.net//gift/Category/Dien_thoai.png",
      "gifts": [
        {
          "category_desc": "Điện thoại di động",
          "category_html": null,
          "category_id": "dien_thoai",
          "category_url": "https://hatto.net//gift/Category/Dien_thoai.png",
          "discount_per": null,
          "dynamic": 0,
          "dynamic_codes": {},
          "expiry_date": null,
          "gift_count": 1,
          "gift_desc": "Smartphone VIP 512G",
          "gift_html": null,
          "gift_id": "dien_thoai_smart_512G",
          "gift_long_desc": null,
          "gift_url": "https://hatto.net//gift/Dien_thoai/dien_thoai_VIP_512g.png",
          "trans_id": ""
        }
      ]
    },
    {
      "category_desc": "Xe cộ",
      "category_html": null,
      "category_id": "xe_co",
      "category_url": "https://hatto.net//gift/Category/Xe_co.png",
      "gifts": [
        {
          "category_desc": "Xe cộ",
          "category_html": null,
          "category_id": "xe_co",
          "category_url": "https://hatto.net//gift/Category/Xe_co.png",
          "discount_per": null,
          "dynamic": 0,
          "dynamic_codes": {},
          "expiry_date": null,
          "gift_count": 1,
          "gift_desc": "Xe đạp ơi",
          "gift_html": null,
          "gift_id": "xe_dap_oi",
          "gift_long_desc": null,
          "gift_url": "https://hatto.net//gift/Xe_co/xe_dap_oi.png",
          "trans_id": ""
        }
      ]
    }
  ],
  "i_can_cook": 1,
  "img_vote_DOWN_count": {
    "6c9154b0-be52-4d83-9bbe-01a7e465b4db.jpg": 0,
    "7d5003c6-d094-487f-be07-948da535e269.jpg": 0,
    "c7d5e5b6-bd5d-482f-a68f-5a574b8a86a7.jpg": 0
  },
  "img_vote_UP_count": {
    "6c9154b0-be52-4d83-9bbe-01a7e465b4db.jpg": 0,
    "7d5003c6-d094-487f-be07-948da535e269.jpg": 0,
    "c7d5e5b6-bd5d-482f-a68f-5a574b8a86a7.jpg": 0
  },
  "info": "PHÁT TRÙM CUỐI",
  "is_guest": false,
  "is_register_totp": false,
  "last_seen": "Thu, 02 Jul 2020 11:00:31 +07",
  "mobile": "0839983428",
  "msg": "OK",
  "next_rank_desc": "Rất sành ăn ",
  "next_rank_dua": 2001,
  "num_friends": 21,
  "num_home_delivery_loc": 2,
  "portrait_url": "https://hatto.net//profile_images//0cea0110-b54d-4406-bc9f-b4ff826dd40c/6182a471-5204-471d-bd86-c72d60b90e87.jpg",
  "predict_count": 156,
  "rank_desc": "Sành ăn ",
  "rank_id": 4,
  "rating_count": 0,
  "remain_GAO": 1127,
  "remain_dua_rank": 1904,
  "rewards": 1705,
  "role_active": 1,
  "role_desc": "Hatto Super-Admin",
  "role_group": null,
  "role_group_desc": null,
  "role_icon": "https://hatto.net//images_SVIP/rank_icons/PNG/super_admin.png",
  "role_id": 1,
  "submit_count": 82,
  "success": true,
  "user_id": "0cea0110-b54d-4406-bc9f-b4ff826dd40c",
  "user_name": "Phát trùm cuối",
  "vote_count": 0,
  "wall_options": {
    "address": false,
    "birthday": true,
    "default_forum_wall": 0,
    "default_sharing_option": 0,
    "email": false,
    "gender": true,
    "mobile": false,
    "wall_view_option": 2
  }
};